<?php
/**
 * PHPaibot - Chatbot API Handler
 * 
 * This file handles communication between the frontend and the webhook API.
 * It processes user messages, sends them to the webhook, and returns responses.
 * It also handles checking for new thoughts generated by the cognitive loop.
 */

// Configuration
$config = [
    'webhook_url' => 'http://localhost:3000/api/chat', // Update with your actual webhook URL
    'thought_file' => __DIR__ . '/data/thoughts.json', // File to store generated thoughts
    'debug' => true // Set to false in production
];

// Ensure data directory exists
if (!file_exists(__DIR__ . '/data')) {
    mkdir(__DIR__ . '/data', 0755, true);
}

// Initialize thoughts file if it doesn't exist
if (!file_exists($config['thought_file'])) {
    file_put_contents($config['thought_file'], json_encode(['thoughts' => []]));
}

// Handle incoming requests
header('Content-Type: application/json');

// Check if this is a thought check request
if (isset($_GET['action']) && $_GET['action'] === 'check_thoughts') {
    handleCheckThoughts();
} else {
    // Process chat message
    handleChatMessage();
}

/**
 * Handle a chat message from the user
 */
function handleChatMessage() {
    global $config;
    
    // Get the request body
    $requestBody = file_get_contents('php://input');
    $data = json_decode($requestBody, true);
    
    // Validate request
    if (!isset($data['message']) || !isset($data['userId'])) {
        sendResponse(['error' => 'Invalid request'], 400);
        return;
    }
    
    $message = $data['message'];
    $userId = $data['userId'];
    $history = isset($data['history']) ? $data['history'] : [];
    
    // Log the request if debug is enabled
    if ($config['debug']) {
        error_log("User message: " . $message);
    }
    
    // In a real implementation, we would call the webhook API
    // For now, we'll simulate a response
    if (isWebhookAvailable()) {
        $response = callWebhookAPI($message, $userId, $history);
    } else {
        // Fallback response if webhook is not available
        $response = [
            'message' => simulateResponse($message),
            'thought' => null
        ];
    }
    
    // Send the response back to the client
    sendResponse($response);
}

/**
 * Handle a request to check for new thoughts
 */
function handleCheckThoughts() {
    global $config;
    
    $userId = isset($_GET['userId']) ? $_GET['userId'] : null;
    
    if (!$userId) {
        sendResponse(['error' => 'User ID is required'], 400);
        return;
    }
    
    // Get thoughts from the file
    $thoughtsData = json_decode(file_get_contents($config['thought_file']), true);
    
    // Check if there's a thought for this user that hasn't been delivered
    $thought = null;
    $thoughtsUpdated = false;
    
    foreach ($thoughtsData['thoughts'] as &$thoughtItem) {
        if ($thoughtItem['userId'] === $userId && !$thoughtItem['delivered']) {
            $thought = $thoughtItem['content'];
            $thoughtItem['delivered'] = true;
            $thoughtsUpdated = true;
            break;
        }
    }
    
    // Save updated thoughts if needed
    if ($thoughtsUpdated) {
        file_put_contents($config['thought_file'], json_encode($thoughtsData));
    }
    
    // Send response
    sendResponse(['thought' => $thought]);
}

/**
 * Check if the webhook API is available
 */
function isWebhookAvailable() {
    global $config;
    
    // In a real implementation, we would check if the webhook is available
    // For now, we'll assume it's not available yet
    return false;
}

/**
 * Call the webhook API
 */
function callWebhookAPI($message, $userId, $history) {
    global $config;
    
    // Prepare the request data
    $requestData = [
        'message' => $message,
        'userId' => $userId,
        'context' => [
            'history' => $history
        ],
        'generateThought' => true
    ];
    
    // Initialize cURL
    $ch = curl_init($config['webhook_url']);
    
    // Set cURL options
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($requestData));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        'Content-Type: application/json'
    ]);
    
    // Execute the request
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    
    // Close cURL
    curl_close($ch);
    
    // Check for errors
    if ($httpCode !== 200) {
        error_log("Webhook API error: HTTP code $httpCode, Response: $response");
        return [
            'message' => "I'm sorry, I'm having trouble connecting to my brain right now. Please try again later.",
            'thought' => null
        ];
    }
    
    // Parse the response
    $responseData = json_decode($response, true);
    
    // Return the response
    return [
        'message' => $responseData['message'] ?? "I'm sorry, I couldn't process your request.",
        'thought' => $responseData['thought'] ?? null
    ];
}

/**
 * Simulate a response (used when webhook is not available)
 */
function simulateResponse($message) {
    // Simple response simulation
    $responses = [
        "I'm still setting up my thinking capabilities. Could you try again later?",
        "My brain is still booting up. I'll be fully operational soon!",
        "I understand you're trying to chat with me, but my neural pathways are still forming.",
        "I'm currently in development mode. Check back soon for a more intelligent conversation!",
        "I'm learning to think like a human. Give me a little more time to develop."
    ];
    
    // Occasionally generate a thought
    if (rand(1, 5) === 1) {
        $thoughts = [
            "I wonder what it means to be conscious...",
            "The internet contains so much information, yet understanding is something different.",
            "Language is fascinating - how words connect to form meaning.",
            "If I could dream, what would I dream about?",
            "Human conversation follows such interesting patterns."
        ];
        
        $thought = $thoughts[array_rand($thoughts)];
        saveThought($thought);
    }
    
    return $responses[array_rand($responses)];
}

/**
 * Save a generated thought
 */
function saveThought($content, $userId = null) {
    global $config;
    
    // Get existing thoughts
    $thoughtsData = json_decode(file_get_contents($config['thought_file']), true);
    
    // Add new thought
    $thoughtsData['thoughts'][] = [
        'id' => uniqid(),
        'userId' => $userId ?? 'system',
        'content' => $content,
        'timestamp' => time(),
        'delivered' => false
    ];
    
    // Save updated thoughts
    file_put_contents($config['thought_file'], json_encode($thoughtsData));
}

/**
 * Send a JSON response
 */
function sendResponse($data, $statusCode = 200) {
    http_response_code($statusCode);
    echo json_encode($data);
    exit;
}
